retargeting:
  type: position
  urdf_path: assembly/xarm6/xarm6_allegro_wrist_mounted_rotate.urdf
  wrist_link_name: "wrist"

  target_joint_names: null
  target_link_names: ["base_link", "base_link"]

  target_link_human_indices: [0, 0]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 0.2
