retargeting:
  type: position
  urdf_path: hands/allegro_hand/allegro_hand_right_free.urdf
  objective_fn_args: 
    target_link_names: [ "link_15.0_tip", "link_3.0_tip", "link_7.0_tip", "link_11.0_tip", "base_link"]

  low_pass_alpha: 0.2
  